### ISSUE TITLE
Issue with a dash live stream

### ISSUE THREAD

**Issue by vikralthakur** [Jayapraveen/Drm-Dash-stream-downloader#2]
```
C:\Users\Downloads\Drm-Dash-stream-downloader-master\Drm-Dash-stream-downloader-master\dashdownloader.py:77: SyntaxWarning: "is" with a literal. Did you mean "=="?
 if video.status_code is 200:
Traceback (most recent call last):
  File "C:\Users\Downloads\Drm-Dash-stream-downloader-master\Drm-Dash-stream-downloader-master\dashdownloader.py", line 142, in <module> video_url,video_keyid,audio_url,audio_keyid = manifest_parser(mpd)
  File "C:\Users\Downloads\Drm-Dash-stream-downloader-master\Drm-Dash-stream-downloader-master\dashdownloader.py", line 60, in manifest_parser
```

```
base_url = repr.base_urls[0].base_url_value
TypeError: 'NoneType' object is not subscriptable
```

Here is the MPD [Link](https://livevoot-i.akamaihd.net/dash/live/828520/colorshd/master.mpd)

**Comment by Jayapraveen** [comment]
The script does not conform to the Dash-IF Implementation guidelines. You'll have to edit the script as per your use case. The MPD you attached is encoded for multibitrate streaming. Edit the dashdownloader_multisegment.py script and handle segments of constant timeframe.
